"""Example Snakefile demonstrating the Guix deployment plugin."""

# This Snakefile showcases how to use Guix for software deployment in Snakemake

# To run this workflow with Guix:
# snakemake --deployment-method guix


rule all:
    input:
        "results/plot.png"


rule download_data:
    output:
        "data/samples.csv"
    shell:
        """
        mkdir -p data
        echo "sample,value" > {output}
        echo "A,10" >> {output}
        echo "B,20" >> {output}
        echo "C,15" >> {output}
        """


rule analyze:
    input:
        "data/samples.csv"
    output:
        "results/analysis.txt"
    conda:  # This conda spec will be automatically converted to Guix
        "envs/analysis.yaml"
    shell:
        """
        mkdir -p results
        python -c "
import pandas as pd
import numpy as np

# Read data
data = pd.read_csv('{input}')

# Analyze
mean = data['value'].mean()
std = data['value'].std()
max_val = data['value'].max()
min_val = data['value'].min()

# Write results
with open('{output}', 'w') as f:
    f.write(f'Mean: {mean}\\n')
    f.write(f'Std: {std}\\n')
    f.write(f'Max: {max_val}\\n')
    f.write(f'Min: {min_val}\\n')
"
        """


rule plot:
    input:
        "results/analysis.txt"
    output:
        "results/plot.png"
    conda:  # This conda spec will be automatically converted to Guix
        "envs/visualization.yaml"
    shell:
        """
        python -c "
import matplotlib.pyplot as plt
import numpy as np

# Read analysis results
with open('{input}', 'r') as f:
    lines = f.readlines()
    
# Extract values
values = {}
for line in lines:
    key, val = line.strip().split(': ')
    values[key] = float(val)

# Create a simple bar chart
plt.figure(figsize=(10, 6))
plt.bar(values.keys(), values.values())
plt.title('Analysis Results')
plt.savefig('{output}')
"
        """
